### ISSUE TITLE
"calmjs.testing"

### ISSUE THREAD

**Issue by jayvdb** [calmjs/calmjs#65]
Is https://github.com/calmjs/calmjs/tree/master/src/calmjs/testing part of the library, or only needed by the tests?

I ask because the tests and `testing` are being included in the *runtime* package of https://build.opensuse.org/package/show/devel:languages:python/python-calmjs , which I am currently fixing, and I want to exclude these from the runtime package if they are not part of the library that users should see.

**Comment by metatoaster** [comment]
Yes, `calmjs.testing` is provided as part of the `calmjs` package to aid developers that want to develop extensions to `calmjs` have access to some common helpers for their test cases.  A number of other `calmjs.*` packages have test cases that import directly from `calmjs.testing` that make use of the utilities provided there.

This package was designed as a development dependency, but for some reason some packages that didn't actually need this depended on this directly and this was the result.  Welcome to the world of Python development.

**Comment by metatoaster** [comment]
To re-emphasize: please DO NOT exclude the tests from the install set.  My package instructions explicitly rely on them for bug reports.

See: https://github.com/calmjs/calmjs#testing-the-installation

**Comment by jayvdb** [comment]
Thanks for your explanation.

Keeping `calmjs.testing` in the package makes lots of sense if other packages are using it, even if only for their testing.

The distro packaging system, in this case, OBS https://github.com/openSUSE/open-build-service, constantly reruns the test suite, whenever any dependency changes, which is why I encountered https://github.com/calmjs/calmjs/issues/64 .

Anyway, I will also leave `calmjs.tests` in the package now, but I cant promise that decision will persist.  I will refer to this issue in the .spec file so whoever next looks into this can at least read your comments here.

**Comment by metatoaster** [comment]
Well, in this case I thank the OBS for identifying an issue with my package for a new release of Python - this is precisely why I have tests available as Python has changed their standard libraries in a way that break my packages (yes experience as a Python developer has taught me this level of paranoia to check for errors even for the bad bumpy paths).  I don't always have the time available to automate all these update/test/alert processes despite Python being too keen to break things.
